name: Python Application Test and Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Test with pytest and coverage
      run: |
        pytest --cov=myapp tests/ --cov-report=xml --cov-report=term-missing
        
    - name: Check coverage threshold
      run: |
        coverage_percentage=$(pytest --cov=myapp tests/ --cov-report=term-missing | grep TOTAL | awk '{print $4}' | sed 's/%//')
        echo "Coverage: $coverage_percentage%"
        if (( $(echo "$coverage_percentage < 70" | bc -l) )); then
          echo "Code coverage is below 70%. Current coverage: $coverage_percentage%"
          exit 1
        fi
        
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml
