name: CI/CD Pipeline

on:
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with coverage
        run: |
          pytest --cov=myapp tests/ --cov-report=xml --cov-report=html
      - name: Check coverage threshold
        run: |
          coverage report --fail-under=70
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/

  build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Build step
        run: |
          echo "Build successful!"
      - name: Update README with build badge
        run: |
          # Перевіряємо, чи бейдж уже існує в README.md
          if [ -f README.md ] && ! grep -q "workflow-badge" README.md; then
            # Якщо бейджа немає, додаємо його
            echo "![workflow-badge](https://github.com/${{ github.repository }}/actions/workflows/ci.yml/badge.svg)" > temp_readme.md
            echo "" >> temp_readme.md
            if [ -f README.md ]; then
              cat README.md >> temp_readme.md
            fi
            mv temp_readme.md README.md
            
            # Комітимо і пушимо зміни в README.md
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add README.md
            git commit -m "Add workflow badge to README [skip ci]"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
